### ISSUE TITLE
Verpine barrel falls off after firing 

### ISSUE THREAD

**Issue by En013** [Special-Operations-Brigade/SOB-Issue-Tracker#331]
Go on training server or hemtt and shoot a Verpine

**Comment by m0kka** [comment]
This happens because the barrels are actually added onto the gun by the magazines. A way to solve this would be to make sure that the magazine does not get automatically consumed when it's empty, but stays in the weapon until reloaded. 

There's a config setting for this for ugl rounds, I just can't remember its name
